### ISSUE TITLE
comparability

### ISSUE THREAD

**Issue by espretto** [keeganstreet/specificity#13] opened 2015-05-14 22:41 UTC
I'm not sure which is the maximum value for per-level-specificity but assuming that limit was 255 one could convert those 4 numbers to one unsigned 32-bit integer as follows:
```js
function toArray (specificity) {
  var i = 4, array = new Array(i);    
  // operator precedence is * before >> before &
  while (i--) array[i] = specificity >> i*8 & 255;
  return array.reverse();
}

function fromArray (array) {
  return array.reverse().reduce(function (specificity, value, i) {
    return specificity + (value << i*8);
  }, 0);
}

/* -----------------------------------------------------------------------------
 * example - from the readme
 */
var foo = SPECIFICITY.calculate('ul#nav li.active a');   // [{ specificity: '0,1,1,3' }]
var bar = SPECIFICITY.calculate('ul#nav li.active a[href]');   // [{ specificity: '0,1,2,3' }]
fromArray(foo.specificity); // 65795
fromArray(bar.specificity); // 66051
```
it's much faster to compare just one instead of four numbers to find out which selector is stronger, plus I wouldn't want to rely on [array comparison](http://wtfjs.com/2013/01/28/array-comparison). another plus is that for most selectors this technique will save some bytes when stringified. inspired by ip-addresses.

**Comment by keeganstreet** [comment] 2016-06-08 10:06
Hi @espretto, thanks for this suggestion. That's an interesting way to approach this. But the problem is that no number of elements will have the same specificity as a classname, even 256 elements will still be beaten by a classname.

I understand it is difficult to compare two arrays, so maybe another solution would be for this calculator to expose a `compare` method. It would make sense to structure it in the same way as the [compare function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) that you can pass to Array.prototype.sort. That is:

```javascript
function compare(a, b) {
  if (a has a lower specificity than b) {
    return -1;
  }
  if (a has a higher specificity than b) {
    return 1;
  }
  // a has the same specificity as b
  return 0;
}
```

**Comment by keeganstreet** [comment] 2016-06-08 11:17
I'm addressing this with https://github.com/keeganstreet/specificity/pull/20

**Comment by keeganstreet** [comment] 2016-06-19 04:02
Resolved with https://github.com/keeganstreet/specificity/pull/20

**Closed by keeganstreet** 2016-06-19 04:02 UTC

**Comment by espretto** [comment] 2016-06-25 19:04
great addition!
